let data = [
  {
    name: "foiegras",
    titleTop: "Нямушка",
    titleBottom: "с фуа-гра",
    portions: "10 порций",
    mice: "мышь в подарок",
    addInfo: "",
    weight: "0,5",
    description: "Печень утки разварная с артишоками.",
    isAvailable: true,
    isChecked: false,
  },
  {
    name: "fish",
    titleTop: "Нямушка",
    titleBottom: "с рыбой",
    portions: "40 порций",
    mice: "2 мыши в подарок",
    addInfo: "",
    weight: "2",
    description: "Головы щучьи с чесноком да свежайшая сёмгушка.",
    isAvailable: true,
    isChecked: true,
  },
  {
    name: "chicken",
    titleTop: "Нямушка",
    titleBottom: "с курой",
    portions: "100 порций",
    mice: "5 мышей в подарок",
    addInfo: "заказчик доволен",
    weight: "5",
    description: "Филе из цыплят с трюфелями в бульоне.",
    isAvailable: false,
    isChecked: false,
  },
];